name: Build and Deploy to Ubuntu Server (No Docker Login)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t finance-manager-backend:latest .

      - name: Save Docker image to tar file
        run: docker save finance-manager-backend:latest -o finance-manager-backend.tar

      - name: Verify tar file locally
        run: |
          file finance-manager-backend.tar
          ls -lh finance-manager-backend.tar

      - name: Copy Docker image tar file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: finance-manager-backend.tar
          target: ~/finance-manager-backend.tar  # explicitly home directory

      - name: Load and run Docker image on server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Listing home directory contents:"
            ls -lh ~/

            cd ~
            if [ ! -f finance-manager-backend.tar ]; then
              echo "ERROR: finance-manager-backend.tar not found!"
              exit 1
            fi

            docker load -i finance-manager-backend.tar

            docker stop backend || true
            docker rm backend || true

            docker run -d --name backend -p 8080:8080 finance-manager-backend:latest
